import { writeFile } from 'node:fs/promises';
import { redactedPatchView } from '../infra/artifacts.js';
import type { RunResult } from '../domain/result.js';
import type { Hypothesis } from '../domain/trajectory.js';
import { describeVerification } from '../domain/verification.js';
import { escapeHtml, htmlDocument, statusClass } from './html.js';

/**
 * Per-run evidence page written next to the other artifacts of that run.
 *
 * The patch is rendered through {@link redactedPatchView}. The report is the
 * artifact people paste into issues and submissions; repair.patch stays exact
 * on disk for checksums and for `apply`.
 */
export async function renderRunReport(
  result: RunResult,
  patchText: string,
  verificationLog: string,
  hypotheses: readonly Hypothesis[],
): Promise<void> {
  const html = buildRunReportHtml(result, redactedPatchView(patchText), verificationLog, hypotheses);
  await writeFile(result.artifacts.reportPath, html, 'utf8');
}

/** `redactedPatch` must already be a redacted view, not the exact patch. */
export function buildRunReportHtml(
  result: RunResult,
  redactedPatch: string,
  verificationLog: string,
  hypotheses: readonly Hypothesis[],
): string {
  const verified = result.verification.kind === 'passed';
  const body = `
<h1>Repro Doctor run ${escapeHtml(result.runId)}</h1>
<p class="subtitle">${escapeHtml(result.mode)} mode on ${escapeHtml(result.caseId ?? 'an unregistered repository')}, model ${escapeHtml(result.model)}</p>

<div class="cards">
  <div class="card"><div class="label">Outcome</div><div class="value ${statusClass(result.outcome.status === 'repaired')}">${escapeHtml(result.outcome.status)}</div></div>
  <div class="card"><div class="label">Hidden oracle</div><div class="value ${statusClass(verified)}">${escapeHtml(result.verification.kind)}</div></div>
  <div class="card"><div class="label">Tool calls</div><div class="value">${result.usage.toolCalls} / ${result.budget.maxToolCalls}</div></div>
  <div class="card"><div class="label">Patch attempts</div><div class="value">${result.usage.patchAttempts} / ${result.budget.maxPatchAttempts}</div></div>
  <div class="card"><div class="label">Wall clock</div><div class="value">${(result.usage.wallClockMs / 1000).toFixed(1)}s</div></div>
  <div class="card"><div class="label">Cost</div><div class="value">${escapeHtml(formatCost(result))}</div></div>
</div>

<h2>Safety</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Executor</td><td>${escapeHtml(result.sandbox.executor)}${result.sandbox.productionSafe ? '' : ' <span class="warn">(test adapter, not an isolation boundary)</span>'}</td></tr>
  <tr><td>Sandbox image</td><td>${escapeHtml(result.sandbox.image ?? 'none')}</td></tr>
  <tr><td>Network during repair</td><td>${escapeHtml(result.sandbox.network)}</td></tr>
  <tr><td>Docker socket in sandbox</td><td>no</td></tr>
  <tr><td>Oracle visible during repair</td><td>no</td></tr>
  <tr><td>Input repository mutated</td><td class="${statusClass(!result.repo.mutated)}">${result.repo.mutated ? 'yes' : 'no'}</td></tr>
  <tr><td>Checksum before</td><td><code>${escapeHtml(result.repo.treeChecksumBefore)}</code></td></tr>
  <tr><td>Checksum after</td><td><code>${escapeHtml(result.repo.treeChecksumAfter)}</code></td></tr>
</table>

<h2>Hypothesis ledger</h2>
${hypotheses.length === 0 ? '<p class="muted">No structured ledger for this run. Baseline mode does not produce one.</p>' : renderLedgerTable(hypotheses)}

<h2>Patch</h2>
${result.patch.kind === 'empty' ? '<p class="muted">The run produced no patch.</p>' : `<p>${result.patch.changedFiles.length} file(s), +${result.patch.addedLines} / -${result.patch.removedLines} lines, sha256 <code>${escapeHtml(result.patch.sha256)}</code> over the exact bytes of <code>repair.patch</code>.</p>
<p class="muted">Shown redacted. <code>repair.patch</code> on disk is exact, unredacted repository content, which is what the checksum and <code>apply</code> need. Review it before publishing it anywhere.</p>
<pre>${escapeHtml(redactedPatch)}</pre>`}

<h2>Independent verification</h2>
<p>${escapeHtml(describeVerification(result.verification))}</p>
<pre>${escapeHtml(verificationLog)}</pre>

<h2>Artifacts</h2>
<ul>
  <li><code>${escapeHtml(result.artifacts.resultPath)}</code></li>
  <li><code>${escapeHtml(result.artifacts.trajectoryPath)}</code></li>
  <li><code>${escapeHtml(result.artifacts.patchPath)}</code></li>
  <li><code>${escapeHtml(result.artifacts.verificationLogPath)}</code></li>
</ul>

<footer>Generated by Repro Doctor from ${escapeHtml(result.artifacts.resultPath)}. Every number on this page comes from that file.</footer>
`;
  return htmlDocument(`Repro Doctor run ${result.runId}`, body);
}

function renderLedgerTable(hypotheses: readonly Hypothesis[]): string {
  const rows = hypotheses
    .map(
      (entry) =>
        `<tr><td><code>${escapeHtml(entry.id)}</code></td><td>${escapeHtml(entry.statement)}</td><td>${escapeHtml(entry.evidence)}</td><td>${escapeHtml(entry.status)}</td></tr>`,
    )
    .join('\n');
  return `<table><tr><th>Id</th><th>Statement</th><th>Evidence</th><th>Status</th></tr>${rows}</table>`;
}

export function formatCost(result: RunResult): string {
  const cost = result.usage.cost;
  if (cost.kind === 'measured') {
    return `$${cost.usd.toFixed(4)}`;
  }
  return `unknown (${cost.why})`;
}
